var pt_PT = {
    Save: "Guardar",
    "Save all": "Guardar tudo",
    Rename: "Renomear",
    Open: "Abrir",
    Edit: "Editar",
    Delete: "Eliminar",
    Folder: "Pasta",
    "Add New": "Adicionar novo",
    Size: "Tamanho",
    Date: "Data",
    "back to parent folder": "voltar à pasta anterior",
    Download: "Transferir",
    Type: "Tipo",
    Information: "Informação",
    Files: "Ficheiros",
    Table: "Tabela",
    Cards: "Cartões",
    Total: "Total",
    "Are you sure ?": "Tem a certeza ?",
    Details: "Detalhes",
    "Enter a new name": "Introduza um novo nome",
    Add: "Adicionar",
    "Select something": "Selecione algo",
    "Download file": "Transferir ficheiro",
    Preview: "Pré-visualizar",
    Refresh: "Atualizar",
    "Are you sure you want to exit without saving?": "Tem a certeza que pretende sair sem guardar?",
    "Save before closing?": "Guardar antes de fechar?",
    Copy: "Copiar",
    Cut: "Cortar",
    Paste: "Colar",
    "Deleting...": "A eliminar...",
    "Copying...": "A copiar...",
    "Moving...": "A mover...",
    Folders: "Pastas",
    "Search results": "Resultados da pesquisa",
    "Search results in": "Resultados da pesquisa em",
    "Search files and folders": "Pesquisar ficheiros e pastas",
    "Add new file": "Adicionar novo ficheiro",
    "Add new folder": "Adicionar nova pasta",
    "Upload file": "Carregar ficheiro",
    folder: "pasta",
    file: "ficheiro",
    archive: "arquivo",
    audio: "áudio",
    image: "imagem",
    video: "vídeo",
    code: "código",
    document: "documento",
    of: "de",
    used: "utilizado",
    "Open item location": "Abrir localização do item",
    "Are you sure you want to delete": "Tem a certeza que pretende eliminar",
    "these items:": "estes itens:",
    "this item:": "este item:",
    "Delete files": "Eliminar ficheiros",
    and: "e",
    "more file(s)": "ficheiro(s) adicional(ais)",
    "Close the editor": "Fechar o editor",
    "Close this file": "Fechar este ficheiro",
    "Owner": "Proprietário",
    "Permissions": "Permissões",
    "Change Permissions": "Alterar permissões",
    "Set": "Definir",
    "Extract": "Extrair",
    "Extract directory": "Diretório de extração",
    "Extracting...": "A extrair...",
    "Compress": "Comprimir",
    "Compressing...": "A comprimir...",
};
